TheatreWebApp/Models/Program/ShowViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TheatreWebApp.Models.Program
{
    public class ShowViewModel
    {
        public int Id { get; set; }

        public string PlayName { get; set; }

        public int PlayId { get; set; }

        public string StageName { get; set; }

        public string ImageUrl { get; set; }

        public string Time { get; set; }
    }
}

TheatreWebApp/Models/Shows/AddShowFormModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TheatreWebApp.Data.Models;

namespace TheatreWebApp.Models.Shows
{
    public class AddShowFormModel
    {
        public int PlayId { get; set; }

        public int StageId { get; set; }

        [Required]
        [RegularExpression(@"[0-9]{2}/[0-9]{2}/[0-9]{4}")]
        public string Date { get; set; }

        [Required]
        [RegularExpression(@"[0-9]{2}:[0-9]{2}")]
        public string Time { get; set; }

        public IEnumerable<Play> Plays { get; set; }

        public IEnumerable<Stage> Stages { get; set; }
    }
}

TheatreWebApp/Models/Shows/EditShowFormModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TheatreWebApp.Models.Shows
{
    public class EditShowFormModel
    {
        public int Id { get; set; }

        [Required]
        [RegularExpression(@"[0-9]{2}/[0-9]{2}/[0-9]{4}")]
        public string Date { get; set; }

        [Required]
        [RegularExpression(@"[0-9]{2}:[0-9]{2}")]
        public string Time { get; set; }
    }
}

TheatreWebApp/Models/Shows/ShowQueryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using TheatreWebApp.Services.Shows.Models;

namespace TheatreWebApp.Models.Shows
{
    public class ShowQueryModel
    {
        public const int ShowsPerPage = 10;

        public int PlayId { get; set; }

        public string SearchTerm { get; set; }

        public string AfterDate { get; set; }

        public string BeforeDate { get; set; }

        public int CurrentPage { get; set; } = 1;

        public int TotalShows { get; set; }

        public IEnumerable<ShowServicePlayModel> Plays { get; set; }

        public IEnumerable<ShowServiceModel> Shows { get; set; }
    }
}

TheatreWebApp/Models/Shows/ShowQueryPlayModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TheatreWebApp.Models.Shows
{
    public class ShowQueryPlayModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

    }
}

TheatreWebApp/Models/Shows/ShowViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TheatreWebApp.Models.Shows
{
    public class ShowViewModel
    {
        public int Id { get; set; }

        public string PlayName { get; set; }

        public int PlayId { get; set; }

        public string StageName { get; set; }

        public string ImageUrl { get; set; }

        public string Time { get; set; }
    }
}

TheatreWebApp/Controllers/PlaysController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TheatreWebApp.Models.Plays;
using TheatreWebApp.Services.Plays;
using TheatreWebApp.Infrastructure;

using static TheatreWebApp.Areas.Admin.AdminConstants;

namespace TheatreWebApp.Controllers
{
    public class PlaysController : Controller
    {
        private readonly IPlayService plays;

        public PlaysController(IPlayService plays)
        {
            this.plays = plays;
        }

        public IActionResult All([FromQuery] PlayQueryModel query)
        {
            var showHidden = false;

            if (this.User.IsAdmin())
            {
                showHidden = true;
            }
            var playsResult = plays.All(query.SearchTerm, query.CurrentPage, showHidden, PlayQueryModel.PlaysPerPage);

            query.TotalPlays = playsResult.TotalPlays;
            query.SearchTerm = playsResult.SearchTerm;
            query.CurrentPage = playsResult.CurrentPage;
            query.Plays = playsResult.Plays;

            return View(query);
        }

        [Authorize(Roles = AdminRoleName)]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = AdminRoleName)]
        public IActionResult Add(PlayFormModel play)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            this.plays.Add(play.Name, play.Description, play.ShortDescription, play.Credits, play.ImageUrl);
            
            return RedirectToAction("All");
        }

        public IActionResult Details(int playId)
        {
            var play = this.plays.Details(playId);

            return View(play);
        }

        [Authorize(Roles = AdminRoleName)]
        public IActionResult Hide(int playId)
        {
            this.plays.ChangeVisibility(playId);

            return RedirectToAction("Details", new { playId = playId});
        }

        [Authorize(Roles = AdminRoleName)]
        public IActionResult Edit(int playId)
        {
            var play = this.plays.FormDetails(playId);

            return View(play);
        }

        [HttpPost]
        [Authorize(Roles = AdminRoleName)]
        public IActionResult Edit(PlayFormModel play)
        {
            this.plays.Edit(play);
           
            return RedirectToAction("Details", new { playId = play.Id});
        }


    }
}

TheatreWebApp/Controllers/ShowsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TheatreWebApp.Models.Shows;
using TheatreWebApp.Services.Shows;
using TheatreWebApp.Infrastructure;

using static TheatreWebApp.Areas.Admin.AdminConstants;

namespace TheatreWebApp.Controllers
{
    public class ShowsController : Controller
    {
        private readonly IShowService shows;

        public ShowsController(IShowService shows)
        {
            this.shows = shows;
        }

        public IActionResult All([FromQuery]ShowQueryModel showQuery)
        {
            var showOlder = false;

            if (this.User.IsAdmin())
            {
                showOlder = true;
            }

            var shows = this.shows.All(
                showQuery.PlayId, 
                showQuery.SearchTerm, 
                showQuery.AfterDate, 
                showQuery.BeforeDate, 
                showQuery.CurrentPage, 
                ShowQueryModel.ShowsPerPage,
                showOlder);

            return View(shows);
        }

        [Authorize(Roles = AdminRoleName)]
        public IActionResult Add()
        {
            var show = this.shows.PrepareForm();
            
            return View(show);
        }

        [HttpPost]
        [Authorize(Roles = AdminRoleName)]
        public IActionResult Add(AddShowFormModel show)
        {
            if(!this.shows.PlayExists(show.PlayId))
            {
                this.ModelState.AddModelError(nameof(show.PlayId), "Play does not exist.");
            }

            if (!this.shows.StageExists(show.StageId))
            {
                this.ModelState.AddModelError(nameof(show.StageId), "Stage does not exist.");
            }

            if (!this.shows.IsDateValid(show.Date))
            {
                this.ModelState.AddModelError(nameof(show.StageId), "Date is not valid. Dates must be in the specified format (dd/MM/yyyy) and no earlier than the present day.");
            }


            if (!ModelState.IsValid)
            {
                var showNew = this.shows.PrepareForm();

                show.Plays = showNew.Plays;
                show.Stages = showNew.Stages;

                return View(show);
            }

            this.shows.Add(show.PlayId, show.StageId, show.Date, show.Time);

            return RedirectToAction("All");
        }

        [Authorize(Roles = AdminRoleName)]
        public IActionResult Edit(int showId)
        {
            var show = this.shows.PrepareEditForm(showId);

            return View(show);
        }

        [HttpPost]
        [Authorize(Roles = AdminRoleName)]
        public IActionResult Edit(EditShowFormModel showForm)
        {
            this.shows.Edit(showForm);

            return RedirectToAction("All");
        }

    }
}

TheatreWebApp/Controllers/TicketsController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TheatreWebApp.Infrastructure;
using TheatreWebApp.Models.Tickets;
using TheatreWebApp.Services.Seats;
using TheatreWebApp.Services.Shows;
using TheatreWebApp.Services.Tickets;

using static TheatreWebApp.WebConstants;

namespace TheatreWebApp.Controllers
{
    public class TicketsController : Controller
    {
        private readonly ISelectionService selection;
        private readonly ITicketService tickets;
        private readonly IShowService shows;

        public TicketsController(ISelectionService selection, ITicketService tickets, IShowService shows)
        {
            this.selection = selection;
            this.tickets = tickets;
            this.shows = shows;
        }

        [Authorize]
        public IActionResult All([FromQuery]TicketQueryModel query)
        {
            var tickets = this.tickets
                .AllByUser(this.User.Id(), query.CurrentPage, TicketQueryModel.TicketsPerPage, query.ShowAll);
                
            return View(tickets);
        }

        [Authorize]
        public IActionResult SelectSeats(int showId)
        {
            if (!this.shows.IsShowAvailable(showId))
            {
                return BadRequest();
            }

            return View(selection.GetSeatingChart(showId));
        }

        [HttpPost]
        [Authorize]
        public IActionResult SelectSeats(BookingFormModel bookingChart)
        {
            if (selection.IsSeatTaken(bookingChart.SelectedSeatId, bookingChart.ShowId))
            {
                this.TempData[GlobalMessageKey] = "Selected seat has already been booked. Please choose another.";

                return RedirectToAction("SelectSeats", new { showId = bookingChart.ShowId });
            }

            return View(selection.GetSeatingChart(bookingChart));
        }

        [Authorize]
        public IActionResult Review(int showId, string selectedSeats)
        {
            var reservations = this.tickets.ReserveSeats(showId, selectedSeats);
            
            if(reservations == null)
            {
                this.TempData[GlobalMessageKey] = "Selected seat has already been booked. Please choose another.";

                return RedirectToAction("SelectSeats", new { showId = showId });
            }

            var tickedId = this.tickets.Create(showId, reservations, this.User.Id());
           
            return View(this.tickets.Review(tickedId));
        }

        [HttpPost]
        [Authorize]
        public IActionResult Review(TicketFormModel ticketForm)
        {
            var isConfirmed = this.tickets.Confirm(ticketForm.TicketId, ticketForm.Action);

            if(isConfirmed == false)
            {
                return RedirectToAction("SelectSeats", new { showId = ticketForm.ShowId });
            }

            return RedirectToAction("All");
        }

        [Authorize]
        public IActionResult Print(string ticketId)
        {
            var userId = this.User.Id();

            var isUserAuthorized = this.tickets.Authorize(userId, ticketId);

            if (!isUserAuthorized)
            {
                return Unauthorized();
            }

            var order = this.tickets.ToPrint(ticketId);

            return View(order);
        }

        [Authorize]
        public IActionResult Cancel(string ticketId)
        {
            this.tickets.Confirm(ticketId, 1);

            return RedirectToAction("All");
        }

        [Authorize]
        public IActionResult Pay(string ticketId)
        {
            this.tickets.Confirm(ticketId, 2);

            return RedirectToAction("All");
        }

    }
}

TheatreWebApp/Views/Shows/Add.cshtml
@using TheatreWebApp.Models.Shows

@model AddShowFormModel

@{
    ViewData["Title"] = "Add Show";
}



<form method="post">
    <div class="col-sm-12 offset-lg-2 col-lg-8">
        <h2 class="text-center">Add show</h2>

        <div class="form-group">
            <label asp-for="PlayId">Play</label>
            <select asp-for="PlayId" class="form-control">
                @foreach (var play in Model.Plays)
                {
                    <option value="@play.Id">@play.Name</option>
                }
            </select>
            <span asp-validation-for="PlayId" class="small text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="StageId">Stage</label>
            <select asp-for="StageId" class="form-control">
                @foreach (var stage in Model.Stages)
                {
                    <option value="@stage.Id">@stage.Name</option>
                }
            </select>
            <span asp-validation-for="StageId" class="small text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Date">Date</label>
            <input asp-for="Date" class="form-control" placeholder="dd/MM/yyyy">
            <span asp-validation-for="Date" class="small text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Time">Time</label>
            <select asp-for="Time" class="form-control">
                <option value="19:00">19:00</option>
                <option value="20:00">20:00</option>
                <option value="21:00">21:00</option>
            </select>
            <span asp-validation-for="Time" class="small text-danger"></span>
        </div>



        <input class="btn btn-primary" type="submit" value="Submit">
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

TheatreWebApp/Views/Shows/All.cshtml
@using TheatreWebApp.Models.Shows

@model ShowQueryModel
@inject SignInManager<User> SignInManager

@{
    ViewData["Title"] = "Program";
}

<div class="text-center">
    <h1>Program</h1>

    @if (User.IsAdmin())
    {
        <p>
            <a asp-action="Add">Add Show</a>
        </p>
    }
</div>


<form method="get">
    <div class="row">
        <div class="form-group col-md-3">
            <div class="form-group">
                <label asp-for="PlayId">Play</label>
                <select asp-for="PlayId" class="form-control">
                    <option value="0">All</option>

                    @foreach (var play in Model.Plays)
                    {
                        <option value="@play.Id">@play.Name</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group col-md-2">
            <label asp-for="SearchTerm">Search by term</label>
            <input asp-for="SearchTerm" class="form-control">
        </div>

        <div class="form-group col-md-3">
            <div class="form-group">
                <label asp-for="AfterDate">After date:</label>
                <input asp-for="AfterDate" class="form-control" placeholder="dd dd/MM dd/MM/yyyy">
            </div>
        </div>

        <div class="form-group col-md-3">
            <div class="form-group">
                <label asp-for="BeforeDate">Before date:</label>
                <input asp-for="BeforeDate" class="form-control" placeholder="dd dd/MM dd/MM/yyyy">
            </div>
        </div>
        <div style="display:flex; justify-content: center; align-items:center">
            <button class="btn btn-primary" type="submit">Search</button>
        </div>
    </div>
</form>



<table class="table table-hover">
    <thead>
        <tr>
            <th style="width: 35%"></th>
            <th></th>
            <th style="width: 30%"></th>
            <th style="width: 25%"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var show in Model.Shows)
        {
            <tr>
                <th scope="row">@show.PlayName</th>
                <td>@show.StageName</td>
                <td><b>@show.Time</b></td>
                <td>
                    @if (show.IsAvailable)
                    {
                        <a class="btn btn-primary" asp-controller="Tickets" asp-action="SelectSeats" asp-route-showId="@show.Id">Book now</a>
                    }

                    <a class="btn btn-primary" asp-controller="Plays" asp-action="Details" asp-route-playId="@show.PlayId">Details</a>

                    @if (User.IsAdmin())
                    {
                        <a class="btn btn-primary" asp-controller="Shows" asp-action="Edit" asp-route-showId="@show.Id">Edit</a>
                    }
                </td>
            </tr>
        }

    </tbody>
</table>

@{
    var previousPage = Model.CurrentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalShows / ShowQueryModel.ShowsPerPage);
}

<div class="row justify-content-center mb-2">

    <div class="col-md-6">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="Shows"
           asp-action="All"
           asp-route-currentPage="@previousPage"
           asp-route-PlayId="@Model.PlayId"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-afterDate ="@Model.AfterDate"
           asp-route-beforeDate ="@Model.BeforeDate"><<</a>
    </div>

    @{
        var shouldButtonBeDisabled = Model.CurrentPage == maxPage ||
                                     !Model.Shows.Any();
    }

    <div class="col-md-6">
        <a class="btn btn-primary float-sm-right @(shouldButtonBeDisabled ? "disabled" : string.Empty)" style="margin-top: 10px"
           asp-controller="Shows"
           asp-action="All"
           asp-route-currentPage="@(Model.CurrentPage + 1)"
           asp-route-PlayId="@Model.PlayId"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-afterDate ="@Model.AfterDate"
           asp-route-beforeDate ="@Model.BeforeDate">>></a>
    </div>
</div>

TheatreWebApp/Views/Shows/Edit.cshtml
@using TheatreWebApp.Models.Shows

@model EditShowFormModel

@{
    ViewData["Title"] = "Edit Show";
}


<form method="post">
    <div class="col-sm-12 offset-lg-2 col-lg-8">
        <h2 class="text-center">Add show</h2>

        <div class="form-group">
            <label asp-for="Date">Date</label>
            <input asp-for="Date" class="form-control" placeholder="dd/MM/yyyy">
            <span asp-validation-for="Date" class="small text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Time">Time</label>
            <select asp-for="Time" class="form-control">
                <option value="19:00">19:00</option>
                <option value="20:00">20:00</option>
                <option value="21:00">21:00</option>
            </select>
            <span asp-validation-for="Time" class="small text-danger"></span>
        </div>

        <input type="hidden" asp-for="Id" value="@Model.Id">
        <input class="btn btn-primary" type="submit" value="Submit">
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}