TheatreWebApp/Models/Seats/CategoryFormModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TheatreWebApp.Models.Seats
{
    public class CategoryFormModel
    {
        public string SelectedSeats { get; set; }

        public IEnumerable<CategoryViewModel> AllCategories { get; set; }

        public IEnumerable<SeatCategoryViewModel> SeatsCategories { get; set; }

        [Required]
        [Display(Name = "Category name")]
        public string CategoryNameInput { get; set; }

        [Required]
        [Display(Name = "Price")]
        public decimal PriceInput { get; set; }
    }
}

TheatreWebApp/Models/Seats/CategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TheatreWebApp.Models.Seats
{
    public class CategoryViewModel
    {
        public string Name { get; set; }

        public decimal Price { get; set; }
    }
}

TheatreWebApp/Models/Seats/SeatCategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TheatreWebApp.Models.Seats
{
    public class SeatCategoryViewModel
    {
        public string StageName { get; set; }

        public string CategoryName { get; set; }

        public string Seats { get; set; }

        public int SeatsCount { get; set; }

        public decimal Price { get; set; }

    }
}

TheatreWebApp/Areas/Admin/Controllers/SeatsController.cs
using Microsoft.AspNetCore.Mvc;
using TheatreWebApp.Models.Seats;
using TheatreWebApp.Services.Categories;
using TheatreWebApp.Services.Seats;
using TheatreWebApp.Services.Seats.Models;

namespace TheatreWebApp.Areas.Admin.Controllers
{
    public class SeatsController : AdminController
    {
        private readonly ISelectionService selection;
        private readonly ICategoryService category;

        public SeatsController(ISelectionService selection, ICategoryService category)
        {
            this.selection = selection;
            this.category = category;
        }

        public IActionResult All()
        {
            var stages = this.selection.All();

            return View(stages);
        }

        public IActionResult Details(int stageId)
        {
            var stage = this.selection.StageDetails(stageId);

            return View(stage);
        }

        [HttpPost]
        public IActionResult Details(StageServiceModel stage)
        {
            stage = this.selection.StageDetails(stage.Id, stage.Name, stage.SelectedSeatId, stage.SelectedSeats, stage.CurrentPage);

            return View(stage);
        }

        public IActionResult Edit(string selectedSeats)
        {
            var categoryDataModel = this.category.GetViewData(selectedSeats);

            var categoryForm = this.category.GetFormModel(categoryDataModel);

            return View(categoryForm);
        }

        [HttpPost]
        public IActionResult Edit(CategoryFormModel categoryInput)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            this.category.EditCategory(categoryInput);

            return RedirectToAction("Edit", new { categoryInput.SelectedSeats });
        }
    }
}

TheatreWebApp/Areas/Admin/Views/Seats/All.cshtml
@using TheatreWebApp.Services.Seats.Models

@model IEnumerable<StageListServiceModel>

@{
    ViewData["Title"] = "Stage Configuration";
}


<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Seat Count</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            @foreach (var stage in Model)
            {
                <tr>
                    <td>
                        @stage.Name
                    </td>
                    <td>
                        @stage.SeatCount
                    </td>
                    <td>
                        <a class="btn btn-primary" asp-controller="Seats"  asp-action="Details" asp-route-stageId="@stage.Id">Details</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

TheatreWebApp/Areas/Admin/Views/Seats/Details.cshtml
@using TheatreWebApp.Services.Seats.Models

@model StageServiceModel

@{
    ViewData["Title"] = "Stage Configuration";
}

<form method="post">
    <div>
        @if (Model.Id == 1)
        {
            <div class="row justify-content-center mb-2">
                <div style="padding: 5px">
                    <button class="btn btn-primary" type="submit" name="currentPage" @(Model.CurrentPage == 1 ? "disabled" : string.Empty) value="1">Stalls</button>
                </div>

                <div style="padding: 5px">
                    <button class="btn btn-primary" type="submit" name="currentPage" @(Model.CurrentPage == 2 ? "disabled" : string.Empty) value="2">Gallery One</button>
                </div>

                <div style="padding: 5px">
                    <button class="btn btn-primary" type="submit" name="currentPage" @(Model.CurrentPage == 3 ? "disabled" : string.Empty) value="3">Gallery Three</button>
                </div>
            </div>
        }




        <input type="hidden" asp-for="Id" value="@Model.Id">
        <input type="hidden" asp-for="Name" value="@Model.Name">
        <input type="hidden" asp-for="CurrentPage" value="@Model.CurrentPage">
        @if (Model.SelectedSeats != null)
        {
            <input type="hidden" asp-for="SelectedSeats" value="@Model.SelectedSeats">
        }


        <partial name="_SeatingChartPartial" model="@Model" />
    </div>
</form>

@if (Model.SelectedSeats != null)
{
<div class="text-center">
    <a class="btn btn-primary" asp-controller="Seats" asp-action="Edit" asp-route-selectedSeats="@Model.SelectedSeats">Edit</a>
</div>

}

TheatreWebApp/Areas/Admin/Views/Seats/Edit.cshtml
@using TheatreWebApp.Models.Seats

@model CategoryFormModel

@{
    ViewData["Title"] = "Edit Seats";
}

<h2 class="text-center">Edit seats</h2>

<table class="table">

    <thead>
        <tr>
            <th>Number of seats</th>
            <th>Category</th>
            <th>Selected seats</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            @foreach (var category in Model.SeatsCategories)
            {
                <tr>
                    <td>
                        @category.SeatsCount
                    </td>
                    <td>
                        @category.CategoryName
                    </td>
                    <td>
                        @category.Seats
                    </td>
                    <td>
                        @category.Price
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<div class="col-sm-12 offset-lg-2 col-lg-8">
    <form method="post">
        <div class="form-group">
            <label>Existing categories: </label>
            <select class="form-control">
                @foreach (var category in Model.AllCategories)
                {
                    <option>@category.Name @category.Price</option>
                }
            </select>
        </div>

        <div class="form-group">
            <label asp-for="CategoryNameInput">Set category of selected seats to:</label>
            <input asp-for="CategoryNameInput" type="text" class="form-control" placeholder="Category name...">
            <span asp-validation-for="CategoryNameInput" class="small text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="PriceInput">Set price of the category:</label>
            <input asp-for="PriceInput" type="text" class="form-control" placeholder="00.00">
            <span asp-validation-for="PriceInput" class="small text-danger"></span>
        </div>
        <input class="btn btn-primary" type="submit" value="Save changes">
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}